### ISSUE TITLE
Github Action to deploy `kube-promtheus-stack-crds` `45.8.1` stuck in _Queued_

### ISSUE THREAD

**Issue by 9numbernine9** [morremeyer/charts#268]
Hello! :wave: 

I was recently trying to upgrade my deployment of `kube-prometheus-stack` to `45.8.1` and noticed that I was running into an issue with fetching the corresponding `kube-promtheus-stack-crds` chart version. Poking around, I noticed that this Github action has been stuck in the _Queued_ state for about five days:
https://github.com/morremeyer/charts/actions/runs/4555775301

I _think_ this is action that "officially" releases the chart to the chart repository, but until it completes I don't think the latest version will be able to be resolved from https://morremeyer.github.io/charts/ . :cry: If someone could take a look it would be greatly appreciated!

**Comment by ekeih** [comment]
My guess is that this was caused by https://www.githubstatus.com/incidents/z3c6q056q332.

I tried to cancel and retry the workflow to publish the release but only get `Failed to cancel workflow.` I am not sure if this is a permission issue or if the workflow is in a really broken state. @morremeyer maybe you can try?

@9numbernine9 Since then two newer versions of the chart have been released, so using the newer versions should work  without any issue (there are no changes in the CRDs).

**Comment by morremeyer** [comment]
Thanks for pinging me here @ekeih.

@9numbernine9 Unfortunately, the incident that @ekeih linked seems to have broken that workflow run completely so that we can't restart it.

You'll need to upgrade to a later version of the chart, which is already available.

Sorry we can't do more here.

**Comment by 9numbernine9** [comment]
@morremeyer No problem - we just wanted to make sure that someone was aware in case there was an issue. We've since upgraded to `45.9.1` and everything is fine now. :+1:
