### ISSUE TITLE
Kube-prometheus-chart CRDs will not work with version v48.0.0

### ISSUE THREAD

**Issue by mymasse** [morremeyer/charts#348]
v48.0.0 was changed so that the CRDs are now in a sub-chart. This means that this line will fail https://github.com/morremeyer/charts/blob/main/.github/workflows/update-kube-prometheus-stack-crds.yml#L32 since the path is now different.

Also looks like no Actions have run since v47.3.0.

**Comment by morremeyer** [comment]
Hey @mymasse, thanks for the report! This will be fixed in https://github.com/community-tooling/charts. 

It looks like I forgot to post the deprecation announcement for this repository, sorry for that (this is why the charts are not updated anymore). 
You can migrate to https://github.com/community-tooling/charts with the same versions that are currently in use in morremeyer/charts and then keep upgrading from there.

I'll update the README asap to note this, sorry about that.

**Comment by morremeyer** [comment]
48.0.0 is released on community-tooling/charts now
